# Generated by Django 5.0.4 on 2024-04-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_acronym', models.CharField(max_length=100)),
                ('currency_name', models.CharField(max_length=100)),
                ('current_rate', models.FloatField()),
                ('last_updated_at', models.DateTimeField(default=None)),
            ],
        ),
    ]
