# Generated by Django 5.0.4 on 2024-05-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_search', '0002_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('component_company', models.CharField(max_length=100)),
                ('component_type', models.CharField(max_length=50)),
                ('component_parameters', models.JSONField()),
            ],
        ),
    ]
