# Generated by Django 5.0.4 on 2024-05-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_search', '0003_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_email', models.CharField(max_length=100)),
                ('message_user_ip', models.CharField(max_length=100)),
                ('message_text', models.CharField(max_length=250)),
                ('message_is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
