# Generated by Django 5.0.4 on 2024-05-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_search', '0004_usermassage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermassage',
            name='message_user_ip',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
